ADMIN_EMAIL:          john@doe.com
ADMIN_GENDER:         male
ADMIN_NAME:           John Doe
ADMIN_PASSWORD:       password
COOKIE_STORE_KEY:     _meetformeal_incredible_session
DEVISE_SECRET:        abc123_devise
FOURSQUARE_TOKEN:     abc123_foursquare
GOOGLE_MAPS_KEY:      abc123_google_maps
GMAIL_PASSWORD:       password
GMAIL_USERNAME:       your.email
ROLES:                admin user # Don't change this line
SECRET_KEY_BASE:      abc123_prod
SECRET_KEY_BASE_DEV:  abc123_dev
SECRET_KEY_BASE_TEST: abc123_test
TEST_EMAIL:           test@test.com
TEST_GENDER:          female
TEST_NAME:            Test Account
TEST_PASSWORD:        password
